version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: solia-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=solia-dev
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - solia-network

  # Backend Express API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solia-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://mongo:27017/solia-dev
      - JWT_SECRET=your_jwt_secret_change_in_production
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - solia-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: solia-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - solia-network

volumes:
  mongo-data:
    driver: local

networks:
  solia-network:
    driver: bridge
