version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://mongo:27017/solia-dev
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
    depends_on:
      - mongo
    command: npm run dev
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    command: npm run dev

volumes:
  mongo-data:
