version: '3.8'

services:
  # MongoDB Database (dev)
  mongo:
    image: mongo:6.0
    container_name: solia-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: solia-dev
    command: mongod --quiet --logpath /dev/null

  # Backend API (dev)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: solia-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=mongodb://mongo:27017/solia-dev
      - JWT_SECRET=dev_jwt_secret
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  # Frontend React (dev)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: solia-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-dev-data:
