#!/usr/bin/env node

/**
 * Safe Cleanup Script
 * 
 * Safely removes validated files after manual review.
 * Requires cleanup-analysis-data.json generated by cleanup-analysis.cjs
 * 
 * Usage:
 *   1. Review CLEANUP_ANALYSIS_REPORT.md
 *   2. Edit this script to uncomment files you want to delete
 *   3. Run: node safe-cleanup.cjs
 */

const fs = require('fs');
const { execSync } = require('child_process');

// Read analysis data
let analysisData;
try {
  analysisData = JSON.parse(fs.readFileSync('cleanup-analysis-data.json', 'utf8'));
} catch (err) {
  console.error('❌ Erreur: Exécutez d\'abord cleanup-analysis.cjs pour générer cleanup-analysis-data.json');
  process.exit(1);
}

console.log('🧹 Script de Nettoyage Sécurisé\n');
console.log(`Fichiers candidats détectés: ${analysisData.potentiallyRemovable.length}\n`);

// FILES TO DELETE - UNCOMMENT AFTER MANUAL VALIDATION
// Décommentez uniquement les fichiers que vous avez validés manuellement
const filesToDelete = [
  // ⚠️ VALIDATION REQUISE: Vérifiez chaque fichier avant de décommenter!
  
  // === OLD TODO FILES ===
  // Uncomment TODO files that are no longer needed:
  // 'TODO.md',
  // 'TODO_API_DOCUMENTATION_UPDATE.md',
  // 'TODO_COMBINED_FRONTEND_BACKEND.md',
  // 'TODO_DOCKER_FIX.md',
  // 'TODO_DOCUMENT_UPLOAD_FIXES.md',
  // 'TODO_ESLINT_FIXES_KYC.md',
  // 'TODO_PHASE_0.md',
  // 'TODO_PHASE_1_IMPLEMENTATION.md',
  // 'TODO_PRIORITAIRE.md',
  // 'TODO_TENANT_SCHEMA_UPDATES.md',
  // 'TODO_TENANT_SC极MA_UPDATES.md',
  // 'TODO_TESTS.md',
  // 'TODO_TS_CORRECTIONS.md',
  // 'TODO_TS_FIXES.md',
  
  // === HTML FILES (STATIC) ===
  // Uncomment if these HTML files are no longer used:
  // 'setup-checklist-visual.html',
  // 'test-results/postman-report.html',
  // 'website/admin/analytics.html',
  // 'website/auth/login.html',
  // 'website/auth/register.html',
  // 'website/dashboard/index.html',
  // 'website/dashboard/investments.html',
  // 'website/dashboard/kyc.html',
  // 'website/dashboard/transactions.html',
  // 'website/index.html',
  // 'website/legal/legal-notice.html',
  // 'website/legal/mentions.html',
  // 'website/legal/terms.html',
  // 'website/properties/index.html',
  
  // === BATCH/POWERSHELL SCRIPTS ===
  // Uncomment if these scripts are no longer referenced:
  // 'start-backend.bat',
  // 'start-server.bat',
  // 'test-backend.ps1',
];

// Safety checks
if (filesToDelete.length === 0) {
  console.log('ℹ️  Aucun fichier à supprimer.');
  console.log('');
  console.log('📋 Instructions:');
  console.log('1. Consultez CLEANUP_ANALYSIS_REPORT.md');
  console.log('2. Éditez safe-cleanup.cjs');
  console.log('3. Décommentez les fichiers à supprimer dans la liste filesToDelete');
  console.log('4. Relancez ce script');
  console.log('');
  process.exit(0);
}

console.log('📝 Fichiers à supprimer:');
filesToDelete.forEach((file, i) => {
  console.log(`   ${i + 1}. ${file}`);
});
console.log('');

// Create backup branch
console.log('💾 Création de la branche de sauvegarde...');
try {
  const currentBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim();
  const backupBranch = `backup-before-cleanup-${Date.now()}`;
  
  execSync(`git checkout -b ${backupBranch}`, { stdio: 'inherit' });
  console.log(`   ✓ Branche de sauvegarde créée: ${backupBranch}`);
  
  execSync(`git push origin ${backupBranch}`, { stdio: 'inherit' });
  console.log(`   ✓ Branche poussée sur origin`);
  
  execSync(`git checkout ${currentBranch}`, { stdio: 'inherit' });
  console.log(`   ✓ Retour à ${currentBranch}\n`);
} catch (err) {
  console.error('❌ Erreur lors de la création de la sauvegarde');
  console.error('   Voulez-vous continuer sans sauvegarde? (Ctrl+C pour annuler)');
  // In a real script, you'd wait for user input here
}

// Delete files
console.log('🗑️  Suppression des fichiers...');
const deleted = [];
const failed = [];

for (const file of filesToDelete) {
  try {
    if (fs.existsSync(file)) {
      execSync(`git rm "${file}"`, { stdio: 'pipe' });
      deleted.push(file);
      console.log(`   ✓ ${file}`);
    } else {
      console.log(`   ⚠️  Fichier introuvable: ${file}`);
      failed.push(file);
    }
  } catch (err) {
    console.error(`   ❌ Erreur: ${file}`);
    failed.push(file);
  }
}

console.log('');

// Summary
if (deleted.length > 0) {
  console.log(`✅ ${deleted.length} fichier(s) supprimé(s)`);
  
  // Calculate space saved
  const spaceFreed = deleted.reduce((sum, file) => {
    const fileData = analysisData.potentiallyRemovable.find(f => f.path === file);
    return sum + (fileData ? fileData.size : 0);
  }, 0);
  
  const formatBytes = (bytes) => {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  };
  
  console.log(`💾 Espace libéré: ${formatBytes(spaceFreed)}`);
  console.log('');
  
  console.log('📝 Prochaines étapes:');
  console.log('   1. Vérifiez les changements: git status');
  console.log('   2. Testez le projet pour confirmer qu\'il fonctionne');
  console.log('   3. Commitez: git commit -m "Clean up: remove unnecessary files"');
  console.log('   4. Poussez: git push origin <branch>');
}

if (failed.length > 0) {
  console.log(`⚠️  ${failed.length} fichier(s) non supprimé(s)`);
  console.log('   Fichiers en échec:');
  failed.forEach(f => console.log(`   - ${f}`));
}

console.log('');
console.log('✅ Nettoyage terminé!');
